//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicEducationEnviroment.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentAnswer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssignmentAnswer()
        {
            this.AssignmentFiles = new HashSet<AssignmentFile>();
        }
    
        public int IdAnswer { get; set; }
        public int IdAssignment { get; set; }
        public int IdStudent { get; set; }
        public Nullable<int> IdTeacher { get; set; }
        public string AnswerText { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public string Grade { get; set; }
    
        public virtual Assignment Assignment { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignmentFile> AssignmentFiles { get; set; }
    }
}
