//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicEducationEnviroment.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentFile
    {
        public int Id { get; set; }
        public int IdAssignmentAnswer { get; set; }
        public string OriginalFileName { get; set; }
        public string StoredFileName { get; set; }
        public string FilePath { get; set; }
    
        public virtual AssignmentAnswer AssignmentAnswer { get; set; }
    }
}
