//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicEducationEnviroment.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseTeacher
    {
        public int id { get; set; }
        public int IdCourse { get; set; }
        public int IdTeacher { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual User User { get; set; }
    }
}
