//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicEducationEnviroment.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseParticipant
    {
        public int Id { get; set; }
        public int IdCourse { get; set; }
        public int IdGroup { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Group Group { get; set; }
    }
}
